language: java
#sudo: required
jdk:
  - openjdk8
services:
install: true
script:
  'ant all -f tools/java/build.xml && ant jar -f tools/java/build.xml && ant check -f tools/cldr-unittest/build.xml -DCLDR_DIR=$(pwd) && ( cd tools/cldr-apps && sh ./install-cldr-jars.sh ) && mvn -f tools/cldr-apps/pom.xml package'
addons:
  apt:
    packages:
      ant

